### ISSUE TITLE
Add OS filtering option to links

### ISSUE THREAD

**Issue by eliasnorrby** [eliasnorrby/dotfiles#37]
Which files to link where may depend on the OS (e.g. VSCode configs), or I may want to use a different source on different platforms.

```yml
links:
  - src: somefile.sh
    os: "MacOSX"
```

## Todo:

- [x] Update `link-topic.yml`
- [x] Check if `unlink-topic.yml` will require updates as well
